version: '3.4'

services:
  mysql:
    image: mysql:8.0  # Fijamos versión para estabilidad
    command: --default-authentication-plugin=mysql_native_password # Para evitar problemas de conexión con PHP antiguos
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes: 
      - mysql_data:/var/lib/mysql
    networks: 
      - backend-network
    restart: always
   
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment: 
      - PMA_ARBITRARY=mysql
    networks: 
      - backend-network
      - frontend-network 
    restart: always
    depends_on: 
      - mysql

  prestashop:
    image: prestashop/prestashop:8.1
    environment: 
      - DB_SERVER=mysql
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_PREFIX=${DB_PREFIX}
      - DB_NAME=${DB_NAME}
      - PS_DOMAIN=${PS_DOMAIN}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_ENABLE_SSL=1
      - PS_INSTALL_AUTO=1
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
    volumes:
      - prestashop_data:/var/www/html
    networks: 
      - backend-network
      - frontend-network
    restart: always
    depends_on: 
      - mysql

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      # Mapea el dominio HTTPS exterior al servicio prestashop puerto 80 interior
      DOMAINS: '${DNS_DOMAIN_SECURE} -> http://prestashop:80' 
      # IMPORTANTE: Si fallas mucho, LetsEncrypt te bloquea. 
      # Para pruebas: STAGE: 'staging'
      # Cuando funcione: STAGE: 'production'
      STAGE: 'production' 
    networks:
      - frontend-network
    depends_on:
      - prestashop

volumes:
  mysql_data:
  prestashop_data:

networks: 
  frontend-network:
  backend-network: